name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Running Script 
      run: |
        cd /home/armaan/actions-runner/_work/homofixproductionV2/homofixproductionV2 
    - name: Running deploy Script 
      run: |
        ./.scripts/deploy.sh
    - name: Restart Gunicorn
      run: |
        # Safely kill the Gunicorn master process - systemd will restart it automatically
        pkill gunicorn || echo "No Gunicorn process found"
